### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by B4rCodee** [Nexon-cc/BetterValthrun#3]
I have a problem where the kdmapper randomly creates a file in C:\Program Files\Google\Chrome can you explain please?
![image](https://github.com/Nexon-cc/BetterValthrun/assets/68064033/1757307d-aaa8-425b-a13f-edae31c3ca09)

**Comment by Nexon-cc** [comment]
IDK. I got kdmapper from unknowncheats. I only put it in the package because it's needed for the cheat
